---
 - hosts: localhost
   connection: local
   gather_facts: False
   become: false
   tasks:
   - ec2_metric_alarm: 
      state: present
      aws_access_key: "AKIAJW4UWPNW4YG5W32Q"
      aws_secret_key: "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"
      region: ap-south-1
      name: "sunil"
      namespace: "AWS/EC2"
      metric: "StatusCheckFailed_System"
      statistic: Maximum
      comparison: ">="
      threshold: 1
      period: 300
      evaluation_periods: 2
      unit: "Count"
      description: "This is for anisble project "
      dimensions: {instance_id: 'i-01eebad0f4c569445'}
...
